### ISSUE TITLE
Speedrun Stark Landing page - Home

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/speedrunstark#1]
## Issue Overview

Starknet speeedrun Adapted from https://github.com/BuidlGuidl/SpeedRunEthereum/tree/master/packages/react-app 

## Proposed Solutions or Ideas

- Implement the main part 
- Change Scaffold-ETH for Scaffold-Stark
- Change Solidity for Cairo

**Comment by jrcarlos2000** [comment]
I have udpated this to `home`
