### ISSUE TITLE
Ch 0: Incorrect label of `wallet not deployed`

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/speedrunstark#111]
## Issue Overview

When you deploy with sepolia and try to do the first login, UI shows a label with a message: `your wallet is not deployed` although it is actually deployed

## Proposed Solutions or Ideas

This issue is not happening in scaffold-stark. Explore scaffold-stark and fix based on it.

## Reproduce issue
Input `git checkout challenge-0-simple-nft`
Deploy with sepolia

**Comment by metalboyrick** [comment]
More information on the above issue since this is a `scaffold-stark` bug
