### ISSUE TITLE
Speedrun - Challenge view

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/speedrunstark#2]
## Issue Overview

Starknet speeedrun Adapted from https://github.com/BuidlGuidl/SpeedRunEthereum/tree/master/packages/react-app 

## Proposed Solutions or Ideas

- Implement the main part 
- Change Scaffold-ETH for Scaffold-Stark
- Change Solidity for Cairo

**Comment by jrcarlos2000** [comment]
## Issue Overview

The main view of the challenge page. : https://speedrunethereum.com/challenge/simple-nft-example 

## Proposed Solutions or Ideas

- the main view of all the challenge pages, it should basically fetch the readme from a branch and display it
- Change Scaffold-ETH for Scaffold-Stark
- Only static ui 
- use Scaffold-eth's reusable components, use mock data for the components that interact with `hooks`
- There is no available smart contracts here
