### ISSUE TITLE
Challenge-0: Current Disconnect option not working on 

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/speedrunstark#28]
## Issue Overview

After you connect your wallet to the website of challenge-01, you can not disconnect it. Devnet/Tesnet not working

## Proposed Solutions or Ideas

- Enable disconnect feature
- Sync up with `scaffold-stark` repo since this feature is working there

**Comment by GabrielaDelPilarR** [comment]
The disconnect button is disabled in the MyNFT view because the connection is automatic, but in the other views it is enabled.
