### ISSUE TITLE
Challenge 0: Repetition of same nft during mint process

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/speedrunstark#29]
## Issue Overview

Since the starknet network take time during mint process, user could mint same mint twice
![2bison](https://github.com/Quantum3-Labs/speedrunstark/assets/22782504/0ccb3c86-6ac3-43a0-822b-6b796addde52)
![2zebra](https://github.com/Quantum3-Labs/speedrunstark/assets/22782504/49f6d904-ccb1-4517-9fa3-07f9df8823ff)

## Proposed Solutions or Ideas

- Fix it using await during mint process
- Disable mint botton until render of first nft has been completed

**Comment by edulanasca** [comment]
@gianalarcon check last commit
