### ISSUE TITLE
Ch1 - Total stake format

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/speedrunstark#37]
## Issue Overview

Provide a brief summary of the issue, including the motivation for addressing it, the problems it presents, and any features required to resolve it.

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by gianalarcon** [comment]
completed on commit  https://github.com/Quantum3-Labs/speedrunstark/commit/602082df2daabbf90449798bb8b6646e96c1f7c8
