### ISSUE TITLE
Ch - 1:  User account balance shows wrong value

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/speedrunstark#41]
## Issue Overview

During testing of challenge-1. After I deploy the contract the UI shows the correct balance of user account,it is 1000 eth

![Screenshot from 2024-04-27 23-39-57](https://github.com/Quantum3-Labs/speedrunstark/assets/22782504/8335a0bf-7700-4382-ab27-25acf4ba0c02)

Then, I do a stake 0.5 operation(I clicked in stake0.5 button ) , so it should decrease the balance of the current user account by 0.5 eth
[
![Screenshot from 2024-04-27 23-03-12](https://github.com/Quantum3-Labs/speedrunstark/assets/22782504/d2f295ac-0e8d-4e12-8d59-cfbc3eca147d)
](url)

In the right top corner of this pic I expect to see 999.499 eth but UI shows 999.0499 eth
On the same picture you can see I called fn `balanceOf` and it retrieves the balance from the blockchain, it shows 9994993...... 

After that I call withdraw operation (click on withdraw button) and I expect to see 999.998 eth but UI shows 999.0998 eth
![Screenshot from 2024-04-27 23-04-59](https://github.com/Quantum3-Labs/speedrunstark/assets/22782504/fd819eb7-bf4e-42f6-9331-da066f77084d)

## Proposed Solutions or Ideas

Fix on UI.

**Comment by edulanasca** [comment]
@gianalarcon if you're in devnet it takes time to refresh the balance, it's a blockchain thing
If you're in sepolia that also takes time to refresh (it happened a lot using Argent)

**Comment by gianalarcon** [comment]
Same challenge, Other finding, it shows balance of the contract is 4.05eth instead of 4.5eth 
![image](https://github.com/Quantum3-Labs/speedrunstark/assets/22782504/43aefcbc-1ed6-41eb-b619-ce8d9872cf1a)

After exploring the code I found the bog here 
https://github.com/Quantum3-Labs/speedrunstark/blob/602082df2daabbf90449798bb8b6646e96c1f7c8/packages/nextjs/hooks/scaffold-stark/useScaffoldEthBalance.ts#L35
