### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/speedrunstark#44]
## Issue Overview

In `challenge-base`
- Read button doesn't have the correct color in **dark mode**. Check [Send] in Write
<img width="608" alt="image" src="https://github.com/Quantum3-Labs/speedrunstark/assets/43045722/c64c3222-2a20-469e-abc1-36d20d0621af">

- In **light mode** the result text doesn't have the correct color
<img width="607" alt="image" src="https://github.com/Quantum3-Labs/speedrunstark/assets/43045722/e082b4a8-cc6e-4034-9927-82c9d17495ee">
 

## Proposed Solutions or Ideas

- Fix these issues in `challenge-base` and then proceed to apply to other branches `simple-nft-example` and `token-vendor`

**Comment by GabrielaDelPilarR** [comment]
It was done in the challenge base
