### ISSUE TITLE
Delayed display of smart contract's balance 

### ISSUE THREAD

**Issue by GabrielaDelPilarR** [Quantum3-Labs/speedrunstark#49]
## Issue Overview

In the token vendor challenge, and possibly in most of the contracts, the Vendor `eth balance` displayed on the `UI` takes time to update or reload. However, querying the blockchain directly through the `debug contract` shows the new `eth balance` immediately.
This happens when deploying in sepolia testnet 
<img width="358" alt="Captura de Pantalla 2024-05-30 a la(s) 09 57 17" src="https://github.com/Quantum3-Labs/speedrunstark/assets/77763655/067ba225-2fb4-41fa-a55d-1476f989a78b">

When you deploy it use rpc https://starknet-sepolia.public.blastapi.io/rpc/v0_5 or a different one in the snfoundry .env

## Proposed Solutions or Ideas

- Implement or update hooks to ensure the UI balance reflects real-time data.
- Compare current `useBalance` performance vs `useScaffoldReadContract`
- Periodically poll the blockchain for balance updates to minimize delays in UI refresh.
- Maybe update the smart contracts
- Test with different rpc providers

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are rewarded via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out team

**Comment by estherbreath** [comment]
If this is still available, can I work on it please?

**Comment by jrcarlos2000** [comment]
sure
@estherbreath

**Comment by estherbreath** [comment]
Thanks

**Comment by estherbreath** [comment]
Hey @jrcarlos2000 
Please is there a telegram group where i can ask questions for a better description?

**Comment by jrcarlos2000** [comment]
https://t.me/+S2OkiwWLWmxjMmJl

**Comment by Dprof-in-tech** [comment]
Gm @gianalarcon 
Im Isaac, a full stack developer with contributions on Onlydust. I would love to work on this issue.

**Comment by gianalarcon** [comment]
All yours @Dprof-in-tech

**Comment by Dprof-in-tech** [comment]
> All yours @Dprof-in-tech

Thank you. I am working on it now. will send a PR soon

**Comment by Dprof-in-tech** [comment]
Hey @gianalarcon , please is there a way I can contact you, I've been trying to get the repo up but its not working

**Comment by gianalarcon** [comment]
Hi @Dprof-in-tech , pls send me a DM to my tg @gianmalarcon
