### ISSUE TITLE
Challenge 1 Decentralized staking: Create Cairo tests

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/speedrunstark#75]
## Issue Overview

Implement  Cairo tests to ensure proper functionality of the smart contract, effectively mirroring the SpeedrunEthereum [test](https://github.com/scaffold-eth/se-2-challenges/blob/challenge-1-decentralized-staking/packages/hardhat/test/Challenge1.ts) of speedrunethereum

## Proposed Solutions or Ideas
- Implement the missing tests for the Cairo version.
- Access the methods of our [components](https://github.com/Quantum3-Labs/speedrunstark/blob/606e728515e6bbb03e2a42c7619d0abd5403094e/packages/snfoundry/contracts/src/YourCollectible.cairo#L44) in the sub-storage and/or use our custom [interfaces/traits](https://github.com/Quantum3-Labs/speedrunstark/blob/606e728515e6bbb03e2a42c7619d0abd5403094e/packages/snfoundry/contracts/src/YourCollectible.cairo#L14).

Take [this](https://github.com/Quantum3-Labs/speedrunstark/blob/decentralized-staking-test/packages/snfoundry/contracts/src/test/TestContract.cairo) progress as a reference.

**Comment by mathstickz** [comment]
would love to work on the issue @gianalarcon

**Comment by gianalarcon** [comment]
Closed on #74
