### ISSUE TITLE
Eth price must be hidden

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/speedrunstark#9]
## Issue Overview

Currently the eth price appears on the bottom left

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by 0xquantum3labs** [comment]
@edulanasca we can use the `useContractRead` function to read from the `ETH_CONTRACT`, we can read the function `balanceOf`. this is a custom implementation of the `useBalance` hook
